name: Checks ğŸ‘€

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Lint ğŸ§¹
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›’
        uses: actions/checkout@v4

      - name: Setup Bun ğŸ°
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies ğŸ”§
        run: bun install

      - name: Lint ğŸ§¹
        run: bun run lint

  typecheck:
    name: Typecheck ğŸ”
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›’
        uses: actions/checkout@v4

      - name: Setup Bun ğŸ°
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies ğŸ”§
        run: bun install

      - name: Typecheck ğŸ”
        run: bun run typecheck

  format:
    name: Format âœ¨
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ğŸ›’
        uses: actions/checkout@v4

      - name: Setup Bun ğŸ°
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies ğŸ”§
        run: bun install

      - name: Format âœ¨
        run: bun run format

      - name: Commit changes ğŸ’¾
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Format âœ¨
